const path = require('path')
const fs = require('fs')

let hooks = {}

let hooksDir = path.join(__dirname, 'hooks')
let hooksList = fs.readdirSync(hooksDir)

hooksList.forEach(name => {
  hooks[name] = fs.readFileSync(path.join(hooksDir, name))
})

let gitDir = path.join(__dirname, '../../.git')
let gitHooksDir = path.join(gitDir, 'hooks')

if (!fs.existsSync(gitDir)) {
  return
}

if (!fs.existsSync(gitHooksDir)) {
  fs.mkdirSync(gitHooksDir)
}

hooksList.forEach(name => {
  let hookPath = path.join(gitHooksDir, name)

  if (
    fs.existsSync(hookPath) &&
    fs.readFileSync(hookPath, 'utf-8').indexOf('generated by git-hooks') < 0
  ) {
    fs.writeFileSync(hookPath + '.back', fs.readFileSync(hookPath))
  }

  fs.writeFileSync(hookPath, hooks[name])
  fs.chmodSync(hookPath, '755')
})
