version: '3'

services:
  code:
    container_name: code-server
    image: codercom/code-server:latest
    restart: always
    ports:
      - 8765:8080
    volumes:
      - /monorepo:/home/coder/project
      # - $HOME/monorepo:/root/projects
