# https://github.com/imlinus/lily-os/commit/62487ea7d42a81a84bc79698e3f77062837ca581

FROM debian:latest

RUN apt-get update

RUN apt install -y gcc
RUN apt install -y cross-gcc-dev
RUN apt install -y ca-certificates
RUN apt install -y build-essential
RUN apt install -y libncurses5
RUN apt install -y libncurses5-dev
RUN apt install -y bison
RUN apt install -y flex
RUN apt install -y libelf-dev
RUN apt install -y libssl-dev
RUN apt install -y bc
RUN apt install -y xorriso
RUN apt install -y make
RUN apt install -y gawk
RUN apt install -y wget
RUN apt install -y tar
RUN apt install -y rsync
RUN apt install -y zsh
RUN apt install -y pv
RUN apt install -y nano
RUN apt install -y lzip
RUN apt install -y texinfo
RUN apt install -y sed
RUN apt install -y gzip

RUN apt-get install -y qemu
