version: '3'

services:
  # --------
  # Services
  # --------

  # abstruse:
  #   extends:
  #     file: ./services/abstruse-ci/docker-compose.yml
  #   ports:
  #     - 1200:8080

  code:
    build: ./services/code
    ports:
      - 1201:8765

  # docs:
  #   container_name: docs
  #   image: etherpad/etherpad
  #   ports:
  #     - '1202:9001'

  # irc:
  #   extends:
  #     file: ./services/irc/docker-compose.yml
  #   ports:
  #     - 1203:1250

  # portainer:
  #   container_name: portainer
  #   image: cr.portainer.io/portainer/agent:2.9.3
  #   restart: always
  #   ports:
  #     - '1204:9001'
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker/volumes:/var/lib/docker/volumes

  # -------
  # Webapps
  # -------

  authenticator:
    build:
      context: ./
      dockerfile: ./webapps/authenticator/Dockerfile
    restart: unless-stopped
    ports:
      - 1300:1300
    command: pnpm start

  # cheatsheets:
  #   build:
  #     context: ./
  #     dockerfile: ./webapps/cheatsheets/Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 1301:1301
  #   command: pnpm start

  # dashboard:
  #   build:
  #     context: ./
  #     dockerfile: ./webapps/dashboard/Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 1302:1302
  #   command: pnpm start

  # fonts:
  #   build:
  #     context: ./
  #     dockerfile: ./webapps/fonts/Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 1303:1303
  #   command: pnpm start

  # notes:
  #   build:
  #     context: ./
  #     dockerfile: ./webapps/notes/Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 1304:1304
  #   command: pnpm start

  personal:
    build:
      context: ./
      dockerfile: ./webapps/personal/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    command: pnpm start

  thrownote:
    build:
      context: ./
      dockerfile: ./webapps/thrownote/Dockerfile
    restart: unless-stopped
    ports:
      - 1305:1305
    command: pnpm start


  # -----
  # Games
  # -----

  # csgo:
  #   image: cm2network/csgo
  #   ports:
  #     - '${CSGO_PORT}:${CSGO_PORT}'
  #   environment:
  #     - SRCDS_RCONPW="${CSGO_ADMIN_PASSWORD}"
  #     - SRCDS_PW="${CSGO_PASSWORD}"
  #     - SRCDS_PORT=${CSGO_PORT}
  #     - SRCDS_TV_PORT=27020
  #     - SRCDS_NET_PUBLIC_ADDRESS="0"
  #     - SRCDS_IP="0"
  #     - SRCDS_FPSMAX=300
  #     - SRCDS_TICKRATE=128
  #     - SRCDS_MAXPLAYERS=14
  #     - SRCDS_STARTMAP="de_dust2"
  #     - SRCDS_REGION=3
  #     - SRCDS_MAPGROUP="mg_active"
  #     - SRCDS_GAMETYPE=0
  #     - SRCDS_GAMEMODE=1
  #     - SRCDS_HOSTNAME="${CSGO_HOSTNAME}"
  #     - ADDITIONAL_ARGS=""

  # minecraft:
  #   image: itzg/minecraft-server
  #   ports:
  #     - '${MINECRAFT_PORT}:${MINECRAFT_PORT}'
