version: '3'

services:
  thrownote:
    build:
      context: ./
      dockerfile: ./webapps/thrownote/Dockerfile
    restart: unless-stopped
    ports:
      - 1337:1337
    command: pnpm start


  # kavita:
  #   image: kizaing/kavita:latest
  #   volumes:
  #     - ./books:/books
  #     - ./data:/kavita/config
  #   ports:
  #     - "5000:5000"
  #   restart: unless-stopped
