version: '3'

services:

  # Services

  css:
    container_name: css
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "1200:3000"
    volumes:
      - ./:/monorepo
    command: sh -c "cd services/css && node server.js"

  fonts:
    container_name: fonts
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "1201:3000"
    volumes:
      - ./:/monorepo
    command: sh -c "cd services/fonts && node server.js"

  
  # Apps

  dashboard:
    container_name: dashboard
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "1300:3000"
    volumes:
      - ./:/monorepo
    command: sh -c "cd apps/dashboard && node server.js"

  personal:
    container_name: personal
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "1301:3000"
    volumes:
      - ./:/monorepo
    command: sh -c "cd apps/personal && node server.js"

  thrownote:
    container_name: thrownote
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "1300:3000"
    volumes:
      - ./:/monorepo
    command: sh -c "cd apps/thrownote && node server.js"
