version: '3.9'

services:
  thrownote:
    container_name: thrownote
    build:
      context: . # ./webapps/thrownote
      dockerfile: Dockerfile.node
      args:
        webapp: thrownote
    ports:
      - "1337:1337"
    volumes:
      - ./webapps/thrownote:/app

  # thrownote:
  #   container_name: thrownote
  #   build: ./webapps/thrownote/
  #   # command: npm start
  #   ports:
  #     - '1337:1337'
  #   volumes:
  #     - ./webapps/thrownote:/app

  # kavita:
  #   image: kizaing/kavita:latest
  #   volumes:
  #     - ./books:/books
  #     - ./data:/kavita/config
  #   ports:
  #     - "5000:5000"
  #   restart: unless-stopped
