version: '3'

services:
  # -----------
  # Third-party
  # -----------
  code:
    container_name: code-server
    image: codercom/code-server:latest
    restart: always
    ports:
      - 8765:8080
    volumes:
      - /monorepo:/home/coder/project
      # - $HOME/monorepo:/root/projects

  docs:
    container_name: docs
    image: etherpad/etherpad
    ports:
      - '${DOCS_PORT}:9001'

  irc:
    container_name: irc
    image: thelounge/thelounge:latest
    ports:
      - '${IRC_PORT}:9000'
    restart: always
    volumes:
      - ~/.thelounge:/var/opt/thelounge

  # ubuntu:
  #   image: ubuntu:rolling
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./:/home

  # -------
  # Webapps
  # -------
  authenticator:
    container_name: authenticator
    build: .
    command: npm start
    ports:
      - '${AUTHENTICATOR_PORT}:${AUTHENTICATOR_PORT}'
    volumes:
      - ./webapps/authenticator:/app

  dashboard:
    container_name: dashboard
    build: .
    command: npm start
    ports:
      - '${DASHBOARD_PORT}:${DASHBOARD_PORT}'
    volumes:
      - ./webapps/dashboard:/app

  notes:
    container_name: notes
    build: .
    command: npm start
    ports:
      - '${DASHBOARD_PORT}:${DASHBOARD_PORT}'
    volumes:
      - ./webapps/notes:/app

  # -----
  # Games
  # -----
  csgo:
    image: cm2network/csgo
    ports:
      - '${CSGO_PORT}:${CSGO_PORT}'
    environment:
      - SRCDS_RCONPW="${CSGO_ADMIN_PASSWORD}"
      - SRCDS_PW="${CSGO_PASSWORD}"
      - SRCDS_PORT=${CSGO_PORT}
      - SRCDS_TV_PORT=27020
      - SRCDS_NET_PUBLIC_ADDRESS="0"
      - SRCDS_IP="0"
      - SRCDS_FPSMAX=300
      - SRCDS_TICKRATE=128
      - SRCDS_MAXPLAYERS=14
      - SRCDS_STARTMAP="de_dust2"
      - SRCDS_REGION=3
      - SRCDS_MAPGROUP="mg_active"
      - SRCDS_GAMETYPE=0
      - SRCDS_GAMEMODE=1
      - SRCDS_HOSTNAME="${CSGO_HOSTNAME}"
      - ADDITIONAL_ARGS=""

  minecraft:
    image: itzg/minecraft-server
    ports:
      - '${MINECRAFT_PORT}:${MINECRAFT_PORT}'
