import path from 'path'
import fs from 'fs'

const isGenerated = path => fs.readFileSync(path, 'utf-8').indexOf('generated by git-hooks') >= 0

let hooks = {}
let hooksList = fs.readdirSync('./hooks')

let gitDir = '../../../.git'
let hooksDir = path.join(gitDir, 'hooks')

if (!fs.existsSync(gitDir)) {
  return
}

if (!fs.existsSync(hooksDir)) {
  return
}

hooksList.forEach(name => {
  let hookPath = path.join(hooksDir, name)
  let hookBackPath = hookPath + '.back'

  let existHook = fs.existsSync(hookPath)
  let hookNeedClean = isGenerated(hookPath)
  let existBack = fs.existsSync(hookBackPath)

  if (hookNeedClean) {
    if (existBack) {
      fs.writeFileSync(hookPath, fs.readFileSync(hookBackPath, 'utf-8'))
      fs.chmodSync(hookPath, '755')
      fs.unlinkSync(hookBackPath)
    } else {
      fs.unlinkSync(hookPath)
    }
  }
})
