name: Shellcheck

# on: [push, pull_request, workflow_dispatch]
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run shellcheck
        run: shellcheck -s sh operating-system/*.sh
